package modelo.pojo;
// Generated 18/10/2017 02:17:40 PM by Hibernate Tools 4.3.1



/**
 * Foo generated by hbm2java
 */
public class Foo  implements java.io.Serializable {


     private int id;
     private String algo;

    public Foo() {
    }

    public Foo(int id, String algo) {
       this.id = id;
       this.algo = algo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getAlgo() {
        return this.algo;
    }
    
    public void setAlgo(String algo) {
        this.algo = algo;
    }




}


