package modelo.pojo;
// Generated 17/10/2017 05:53:02 PM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private int id;
     private String correo;
     private String clave;

    public Login() {
    }

    public Login(int id, String correo, String clave) {
       this.id = id;
       this.correo = correo;
       this.clave = clave;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


